name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- State Management ---
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # --- Architecture Core ---
  dartz: ^0.10.1

  # --- Network ---
  get_it: ^7.6.0
  dio: ^5.4.0
  internet_connection_checker_plus: ^2.5.1

  # --- Local DB ---
  sqflite: ^2.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.2

  # --- Maps & Location ---
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2

  # --- Hardware ---
  image_picker: ^1.0.4
  qr_code_scanner: ^1.0.1
  connectivity_plus: ^6.1.5

  # --- UI Utils ---
  google_fonts: ^6.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/puskonet.png
